### ISSUE TITLE
Meaning of variables

### ISSUE THREAD

**Issue by davixcky** [zeppelsoftware/bluebub#3]
Hey, thanks for this lib. I want to understand a little bit how it works, but the calculus that you do is not clear.

Can you provide a little clarification on the meaning of that part of the code? For example on the creation of this variables
```
    private int p = 14;
    private int s = 2;
    private int pm = 10;
    private int sm = 2;
```

Also can you extend on the why of the calculus for the width?

Thanks in advance.

**Comment by b3z** [comment]
Hey mate.

So `p` is basically the [padding](https://wiki.selfhtml.org/images/thumb/f/f3/Box-Modell.svg/1024px-Box-Modell.svg.png) around the text (top, bottom, left and right).

`s` is the side space of the text. So it just adds to the padding `p` in same scale but only on the sides (left and right).

`pm, sm` are the same but for the meta texts.

About the width calculations. I assume you mean [this](https://github.com/zeppelsoftware/bluebub/blob/master/bluebub/Bubble.java#L111) line.

```java
int w = textW + p * 2 + s * 2;
int h = textH + p * 2;
```

So we want to know the width of the rectangle we want to draw later. Thus we take the [width of the text](https://github.com/zeppelsoftware/bluebub/blob/master/bluebub/Bubble.java#L109) and add the padding times two (for left and right). Also we add the sidespace variable times two since this is an addition to the padding (only left and right).

For the height we do the same with the height of the text and this time only the padding since we don't want additional space on the top or the bottom.

Hope that answers your questions otherwise just ask again.

**Comment by davixcky** [comment]
Hey, 

Thanks for the clarification was really helpful.
